### ISSUE TITLE
Check third side

### ISSUE THREAD

**Issue by griggszm** [dennis-classes/se2832-lab-01-isosceles-BradWasilewski1021#1]
The size of the third side is not being correctly checked: it marks 5.0 1.0 999999 as valid dimensions

**Comment by BradWasilewski1021** [comment]
Is the problem that 999999 is incorrect dimension, or that 5.0 + 1.0 !> 999999?

**Comment by griggszm** [comment]
5.0 + 1.0 is not greater than 99999, so this should be checked and marked invalid in the case of a+b>c
